# -*- coding: utf-8 -*-


class ServicoAdicional(object):

    AVISO_RECEBIMENTO = 1
    MAO_PROPRIA_NACIONAL = 2
    VALOR_DECLARADO_NACIONAL = 19
    REGISTRO_NACIONAL = 25
    AVISO_DE_RECEBIMENTO_DIGITAL = 37
    DEVOLUCAO_DE_NOTA_FISCAL_SEDEX = 49
    TAXA_DE_ENTREGA_DE_ENCOMENDA_DESPADRONIZADA = 57
    LOGISTICA_REVERSA_SIMULTANEA_DOMICILIARIA = 67
    LOGISTICA_REVERSA_SIMULTANEA_EM_AGENCIA = 69

    def __init__(self, codigo):
        self.codigo = codigo


